schema_version: 1

context:
  name: jujutsu
  version: "0.32.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/jj-vcs/jj/archive/v${{ version }}.tar.gz
  sha256: 12b8e65b7950b189d1df7e20cc55e20ff9cc2bd8d520847323b80daa1cddb27b

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - ${{ stdlib("c") }}
    - cargo-bundle-licenses
    - if: linux
      then: pkg-config
  host:
    - if: linux
      then: openssl

tests:
  - script:
      - jj --help
      - jj git clone --colocate https://github.com/conda-forge/status.git
  - package_contents:
      bin:
        - jj

about:
  summary: A Git-compatible VCS that is both simple and powerful
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  description: |
    Jujutsu is a powerful version control system for software projects. 
    You use it to get a copy of your code, track changes to the code, and 
    finally publish those changes for others to see and use. It is designed 
    from the ground up to be easy to use—whether you're new or experienced, 
    working on brand new projects alone, or large scale software projects 
    with large histories and teams.
  homepage: https://jj-vcs.github.io/jj
  repository: https://github.com/jj-vcs/jj

extra:
  recipe-maintainers:
    - synapticarbors
